import { DatabaseSchema } from "@/lib/types";

export const INITIAL_DB_DATA: DatabaseSchema = {
  siteSettings: {
    id: "mcoe-settings-2026",
    academicTenure: "2026–2027",
    instagramUrl: "https://www.instagram.com/pesmoderncoe_pune?stkn=MWFmcjNyMXZyaDh6bQ==",
    instagramHandle: "@pesmoderncoe_pune",
    whatsappChannelUrl: "https://whatsapp.com/channel/0029Vb7CCvG3rZZcpzCcZY3I",
    officialEmail: "studentscouncil@moderncoe.edu.in",
    contactPhone1: "+91 20 2553 3638",
    contactPhone2: "+91 98220 12345",
    annualBrochurePdfUrl: "#brochure",
    codeOfConductPdfUrl: "#code-of-conduct",
    collegeAddress: "1186/A, Off J.M. Road, Shivajinagar, Pune, Maharashtra 411005",
    affiliationNotice: "Affiliated to Savitribai Phule Pune University (SPPU) | Approved by AICTE & NAAC 'A+' Accredited",
    updatedAt: new Date().toISOString(),
  },
  anonymousQueries: [
    {
      id: "anon-001",
      trackingToken: "ANON-MCOE-8492-X7",
      category: "Academic / Timetable / Exam Query",
      departmentScope: "General / Campus-wide",
      urgency: "MEDIUM",
      subject: "Request for Extended Central Library Reading Hall Hours during SPPU In-Sem / End-Sem Exams",
      description: "During university examination months, many hosteller and day-scholar students struggle to find a quiet study zone in the evenings. Can the Students' Council request the administration to extend the Central Library Reading Hall timings up to 10:00 PM?",
      allowPublicDisplay: true,
      status: "RESOLVED",
      officialCouncilResponse: "The Students' Council formally represented this matter to Principal Dr. K. R. Joshi and Chief Librarian. Permission has been granted: The Central Library Ground Floor & Mezzanine Reading Halls will remain open from 8:00 AM to 10:00 PM on all weekdays and Saturdays during the exam period, with campus security and biometric access active.",
      responseTimestamp: "2026-09-28T14:30:00.000Z",
      isPubliclyPublished: true,
      isReviewed: true,
      createdAt: "2026-09-25T10:15:00.000Z",
      updatedAt: "2026-09-28T14:30:00.000Z",
    },
    {
      id: "anon-002",
      trackingToken: "ANON-MCOE-3109-P4",
      category: "Infrastructure / Classroom / Lab / Wi-Fi Issue",
      departmentScope: "Artificial Intelligence & Data Science",
      urgency: "HIGH",
      subject: "Wi-Fi Connectivity Drops in AI & DS and IT Advanced Computing Labs (Building B, 3rd Floor)",
      description: "Students during machine learning project practicals and hackathon preparation experience frequent network drops on the campus SSID in Lab B-304 and B-305.",
      allowPublicDisplay: true,
      status: "RESOLVED",
      officialCouncilResponse: "Secretary of Website Operations & Technical Wing escalated this directly to the Central IT Infrastructure Cell. Two new dual-band enterprise Aruba Wi-Fi 6 Access Points have been deployed and tuned in the 3rd Floor Building B corridor, restoring 150+ Mbps speed.",
      responseTimestamp: "2026-10-02T11:00:00.000Z",
      isPubliclyPublished: true,
      isReviewed: true,
      createdAt: "2026-09-29T16:20:00.000Z",
      updatedAt: "2026-10-02T11:00:00.000Z",
    },
    {
      id: "anon-003",
      trackingToken: "ANON-MCOE-7721-M9",
      category: "Washroom / Hygiene / Canteen / Water Facility",
      departmentScope: "General / Campus-wide",
      urgency: "MEDIUM",
      subject: "Periodic Filter Replacement and UV Servicing of RO Water Dispensers in Mechanical/Civil Quadrangle",
      description: "The RO water dispenser on the 2nd Floor Mechanical building had low water pressure and required filter maintenance.",
      allowPublicDisplay: true,
      status: "RESOLVED",
      officialCouncilResponse: "Estate & Maintenance Cell replaced the RO membrane and activated carbon filter candles on October 3, 2026. Water quality TDS testing certified within permissible standard (95 PPM). Daily inspection log posted on the dispenser unit.",
      responseTimestamp: "2026-10-04T09:45:00.000Z",
      isPubliclyPublished: true,
      isReviewed: true,
      createdAt: "2026-10-01T12:00:00.000Z",
      updatedAt: "2026-10-04T09:45:00.000Z",
    },
    {
      id: "anon-004",
      trackingToken: "ANON-MCOE-9543-K2",
      category: "Safety / Ragging / Harassment / Welfare Concern",
      departmentScope: "General / Campus-wide",
      urgency: "HIGH",
      subject: "Improved Lighting and CCTV Coverage along the Rear Gate Parking Pathway",
      description: "The pathway connecting the rear parking lot near the sports ground needs additional high-illumination floodlights for students leaving late from robotics and cultural evening rehearsals.",
      allowPublicDisplay: false,
      status: "UNDER_REVIEW",
      officialCouncilResponse: "The Ladies' Representative and General Secretary inspected the route with the Campus Security Supervisor. Proposal submitted to the Management Committee for 3 solar LED high-mast poles and 2 additional 4K bullet CCTV cameras. Expected installation within 10 days.",
      responseTimestamp: "2026-10-05T15:10:00.000Z",
      isPubliclyPublished: false,
      isReviewed: true,
      createdAt: "2026-10-04T18:05:00.000Z",
      updatedAt: "2026-10-05T15:10:00.000Z",
    },
  ],
  events: [
    {
      id: "evt-001",
      slug: "m-pulse-2027",
      title: "M-PULSE 2027: National Level Technical Symposium",
      category: "FLAGSHIP",
      shortDescription:
        "PES MCOE’s premier annual technical fest featuring 12+ mega tracks: National Coding League, Robo-Wars, AI Project Expo, CAD Masters, and WebCraft.",
      fullDescription:
        "M-PULSE is the flagship national-level technical symposium of PES's Modern College of Engineering, Pune. Uniting over 3,000+ engineering minds from across Maharashtra and premier pan-India colleges, M-PULSE 2027 provides an electrifying arena to test your coding prowess, hardware engineering, paper presentations, and algorithmic mastery.",
      rules: [
        "Open to all undergraduate & postgraduate engineering students with valid College ID.",
        "Teams can consist of 1 to 4 members depending on individual sub-event tracks.",
        "Participants must adhere to the official SPPU Code of Conduct.",
        "Plagiarism in Project Expo or Coding tracks will result in immediate disqualification.",
        "Decision of the Jury & Technical Wing Office Bearers will be final and binding.",
      ],
      eventDate: "2027-02-19",
      time: "09:00 AM – 06:00 PM (2 Days)",
      venue: "PES MCOE Campus, Auditorium, Seminar Halls & Advanced Labs",
      organizingWing: "Technical Wing & Departmental Student Associations",
      entryFee: "₹100 / Member (Free for PES MCOE Students)",
      prizePool: "₹1,50,000+ Cash Prizes, Trophies & Industry Vouchers",
      posterUrl: "https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?auto=format&fit=crop&w=1200&q=80",
      rulebookPdfUrl: "#rulebook-mpulse",
      schedule: [
        { time: "Day 1, 09:30 AM", activity: "Grand Inaugural Ceremony & Keynote Address", details: "Main College Auditorium" },
        { time: "Day 1, 11:00 AM", activity: "National Coding League & AI Hack Round 1", details: "Central Computing Center" },
        { time: "Day 1, 02:00 PM", activity: "Robo-Wars & Circuit Debugging Prelims", details: "Mechanical Quadrangle Arena" },
        { time: "Day 2, 10:00 AM", activity: "Hardware & Software Project Expo Showcase", details: "Building B Concourse" },
        { time: "Day 2, 04:00 PM", activity: "Valedictory Function & Prize Distribution", details: "Auditorium" },
      ],
      coordinatorName: "Atharva Joshi (Technical Secretary)",
      coordinatorPhone: "+91 98221 54321",
      eligibility: "Open to All Engineering / Tech Colleges Nationwide",
      status: "UPCOMING",
      isFeatured: true,
      registrationOpen: true,
      createdAt: "2026-09-15T00:00:00.000Z",
    },
    {
      id: "evt-002",
      slug: "spandan-2027",
      title: "SPANDAN 2027: Annual Social Gathering & Cultural Fest",
      category: "FLAGSHIP",
      shortDescription:
        "The heartbeat of Modernites — Celebrating dance, theatrical drama, music band wars, fashion runway, and cultural heritage.",
      fullDescription:
        "Spandan is the annual social gathering and flagship cultural fiesta of PES MCOE Pune. Featuring an unmatched celebration of Maharashtra's traditional performing arts alongside contemporary musical showdowns, Spandan unites the entire campus in a vibrant kaleidoscope of joy, camaraderie, and student creativity.",
      rules: [
        "Exclusive to PES MCOE students and invited alumni.",
        "College Identity Card mandatory at the security gate at all times.",
        "Auditions mandatory for Dance, Music, and Drama tracks.",
        "Costumes and stage props must be pre-approved by the Cultural Staff Advisory Committee.",
      ],
      eventDate: "2027-01-28",
      time: "10:00 AM – 09:30 PM (3 Days)",
      venue: "PES MCOE Main Amphitheater & Open-Air Grounds",
      organizingWing: "Cultural Wing, Students’ Council",
      entryFee: "Free Entry for all MCOE Students",
      prizePool: "Trophies, Certificates of Distinction & Rolling Shields",
      posterUrl: "https://images.unsplash.com/photo-1514525253161-7a46d19cd819?auto=format&fit=crop&w=1200&q=80",
      rulebookPdfUrl: "#rulebook-spandan",
      schedule: [
        { time: "Day 1, 10:00 AM", activity: "Traditional Day, Dhol Tasha & Folk Dance Showcase", details: "Main Quadrangle" },
        { time: "Day 2, 02:00 PM", activity: "Battle of the Bands & Acoustic Vocals", details: "Open Stage" },
        { time: "Day 2, 06:30 PM", activity: "Purushottam Karandak Theatrical Night", details: "Auditorium" },
        { time: "Day 3, 05:00 PM", activity: "Grand Group Dance Finale & DJ Night", details: "Main Stage" },
      ],
      coordinatorName: "Siddhi Shinde (Cultural Secretary)",
      coordinatorPhone: "+91 97654 12389",
      eligibility: "PES MCOE Students Only",
      status: "UPCOMING",
      isFeatured: true,
      registrationOpen: true,
      createdAt: "2026-09-20T00:00:00.000Z",
    },
    {
      id: "evt-003",
      slug: "hack-ai-2027",
      title: "HACK-AI 2027: 36-Hour National AI & Data Science Hackathon",
      category: "TECHNICAL",
      shortDescription:
        "Build generative AI agents, computer vision pipelines, and scalable cloud solutions solving real-world civic and industrial challenges.",
      fullDescription:
        "Organized jointly by the Students' Council Technical Wing and the CoDE Club (Department of Artificial Intelligence & Data Science), HACK-AI 2027 brings together top collegiate hackers. Mentored by AI research scientists and industry architects.",
      rules: [
        "Team size: 2 to 4 members.",
        "All code must be written during the 36-hour hackathon window.",
        "GitHub repositories with commit history will be verified during jury rounds.",
        "Use of open-source models and APIs is permitted with proper disclosure.",
      ],
      eventDate: "2027-03-12",
      time: "08:00 AM (Friday) to 08:00 PM (Saturday)",
      venue: "AI & Data Science Advanced Analytics Center, Building B",
      organizingWing: "CoDE Club & Council Technical Wing",
      entryFee: "₹400 / Team (Includes Food, High-Speed Wi-Fi & Swag Kit)",
      prizePool: "₹75,000 Cash Pool + Cloud Credits & Summer Internships",
      posterUrl: "https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?auto=format&fit=crop&w=1200&q=80",
      rulebookPdfUrl: "#rulebook-hackai",
      schedule: [
        { time: "Friday, 08:30 AM", activity: "Check-in, Wi-Fi onboarding & Problem Statement Reveal" },
        { time: "Friday, 11:00 AM", activity: "Hacking Begins — Round 1 Architecture Pitch" },
        { time: "Saturday, 02:00 AM", activity: "Midnight Mentorship Checkpoint & Energy Surge" },
        { time: "Saturday, 05:00 PM", activity: "Final Code Freeze & Jury Demos" },
      ],
      coordinatorName: "Varun Nair (Secretary of Website Operations)",
      coordinatorPhone: "+91 98900 45678",
      eligibility: "Open to All College Undergraduates",
      status: "UPCOMING",
      isFeatured: true,
      registrationOpen: true,
      createdAt: "2026-09-25T00:00:00.000Z",
    },
    {
      id: "evt-004",
      slug: "shaurya-sports-meet-2027",
      title: "SHAURYA 2027: Inter-Departmental Annual Sports Olympiad",
      category: "SPORTS",
      shortDescription:
        "High-octane cricket, football, basketball, volleyball, table tennis, chess, and track & field athletics for the coveted Champion's Trophy.",
      fullDescription:
        "Shaurya 2027 is the annual multi-sport fiesta of PES MCOE. 9 departments clash across outdoor and indoor disciplines to claim the prestigious General Championship Trophy.",
      rules: [
        "Players must represent their respective academic department.",
        "Official department sports jersey mandatory during matches.",
        "Referee decisions are final; unsporting conduct will lead to team point deduction.",
      ],
      eventDate: "2027-01-15",
      time: "07:30 AM – 06:00 PM (4 Days)",
      venue: "PES Sports Complex & College Ground, Shivajinagar",
      organizingWing: "Sports Wing, Students’ Council",
      entryFee: "Free Registration through Department Sports Heads",
      prizePool: "General Championship Rolling Trophy, Medals & Certificates",
      posterUrl: "https://images.unsplash.com/photo-1461896836934-ffe607ba8211?auto=format&fit=crop&w=1200&q=80",
      rulebookPdfUrl: "#rulebook-shaurya",
      schedule: [
        { time: "Day 1, 08:00 AM", activity: "Sports March-Past & Torch Relay by SPPU Athletes" },
        { time: "Day 1 to 3", activity: "Inter-Department League Matches (Cricket, Football, Basketball)" },
        { time: "Day 4, 03:30 PM", activity: "Grand Finals & Trophy Presentation Ceremony" },
      ],
      coordinatorName: "Omkar Patil (Sports Secretary)",
      coordinatorPhone: "+91 94230 78912",
      eligibility: "PES MCOE Department Teams",
      status: "UPCOMING",
      isFeatured: false,
      registrationOpen: true,
      createdAt: "2026-09-28T00:00:00.000Z",
    },
    {
      id: "evt-005",
      slug: "nss-mega-blood-donation-2026",
      title: "NSS Mega Blood Donation Camp & Health Checkup Drive",
      category: "NSS_SOCIAL",
      shortDescription:
        "Giving back to society: In association with Sassoon General Hospital & AFMC Pune. Free health checkup and donor donor certificates.",
      fullDescription:
        "The National Service Scheme (NSS) unit of PES MCOE in coordination with the Students' Council organizes the annual Mega Blood Donation Camp, upholding the legacy of Progressive Education Society.",
      rules: [
        "Donors must be at least 18 years of age and weigh 45kg or above.",
        "Free hemoglobin and general health assessment provided before donation.",
        "Refreshments and official Govt Blood Donor Card provided to all donors.",
      ],
      eventDate: "2026-11-14",
      time: "09:00 AM – 05:00 PM",
      venue: "College Auditorium Foyer, Ground Floor",
      organizingWing: "NSS Unit & Council Welfare Wing",
      entryFee: "Free (Noble Cause)",
      prizePool: "Govt Donor Certificate & Sassoon Donor Badge",
      posterUrl: "https://images.unsplash.com/photo-1615461066841-6116e61058f4?auto=format&fit=crop&w=1200&q=80",
      rulebookPdfUrl: "#rulebook-nss",
      schedule: [
        { time: "09:00 AM", activity: "Inauguration by Medical Superintendents & Principal" },
        { time: "09:30 AM to 05:00 PM", activity: "Continuous Blood Collection & Donor Care" },
      ],
      coordinatorName: "Pooja Gaikwad (NSS Coordinator)",
      coordinatorPhone: "+91 91580 34567",
      eligibility: "Open to Students, Faculty, Alumni & Citizens",
      status: "UPCOMING",
      isFeatured: false,
      registrationOpen: true,
      createdAt: "2026-10-01T00:00:00.000Z",
    },
  ],
  councilMembers: [
    // Faculty Advisory Board
    {
      id: "mem-001",
      name: "Dr. (Mrs.) K. R. Joshi",
      designation: "Principal & Chief Patron",
      wing: "FACULTY",
      department: "Electronics & Telecommunication",
      tenure: "2026–2027",
      photoUrl: "",
      email: "principal@moderncoe.edu.in",
      displayOrder: 1,
      isActive: true,
    },
    {
      id: "mem-002",
      name: "Dr. (Mrs.) S. A. Itkar",
      designation: "Vice Principal",
      wing: "FACULTY",
      department: "AI & ML",
      tenure: "2026–2027",
      photoUrl: "",
      email: "viceprincipal@moderncoe.edu.in",
      displayOrder: 2,
      isActive: true,
    },
    {
      id: "mem-003",
      name: "Prof. Dr. S. N. Chaphekar",
      designation: "Student Development Officer (SDO) / Staff Advisor",
      wing: "FACULTY",
      department: "Mechanical Engineering",
      tenure: "2026–2027",
      photoUrl: "",
      email: "sdo@moderncoe.edu.in",
      displayOrder: 3,
      isActive: true,
    },
    // Executive Core Council
    {
      id: "mem-004",
      name: "Rohan V. Kulkarni",
      designation: "General Secretary (GS)",
      wing: "CORE",
      department: "Computer Engineering",
      year: "BE",
      tenure: "2026–2027",
      photoUrl: "",
      linkedinUrl: "https://linkedin.com",
      instagramUrl: "https://instagram.com",
      email: "gs.council@moderncoe.edu.in",
      displayOrder: 4,
      isActive: true,
    },
    {
      id: "mem-005",
      name: "Ananya S. Deshmukh",
      designation: "Joint General Secretary",
      wing: "CORE",
      department: "Information Technology",
      year: "BE",
      tenure: "2026–2027",
      photoUrl: "",
      linkedinUrl: "https://linkedin.com",
      email: "jointgs.council@moderncoe.edu.in",
      displayOrder: 5,
      isActive: true,
    },
    {
      id: "mem-006",
      name: "Aditya P. Shinde",
      designation: "Treasurer / Finance Coordinator",
      wing: "CORE",
      department: "Mechanical Engineering",
      year: "BE",
      tenure: "2026–2027",
      photoUrl: "",
      linkedinUrl: "https://linkedin.com",
      email: "treasurer.council@moderncoe.edu.in",
      displayOrder: 6,
      isActive: true,
    },
    // Portfolio Secretaries
    {
      id: "mem-007",
      name: "Atharva Joshi",
      designation: "Technical Secretary",
      wing: "SECRETARY",
      department: "AI & DS",
      year: "TE",
      tenure: "2026–2027",
      photoUrl: "",
      linkedinUrl: "https://linkedin.com",
      email: "tech.council@moderncoe.edu.in",
      displayOrder: 7,
      isActive: true,
    },
    {
      id: "mem-008",
      name: "Siddhi Shinde",
      designation: "Cultural Secretary",
      wing: "SECRETARY",
      department: "E&TC",
      year: "TE",
      tenure: "2026–2027",
      photoUrl: "",
      linkedinUrl: "https://linkedin.com",
      email: "cultural.council@moderncoe.edu.in",
      displayOrder: 8,
      isActive: true,
    },
    {
      id: "mem-009",
      name: "Omkar Patil",
      designation: "Sports Secretary",
      wing: "SECRETARY",
      department: "Electrical Engineering",
      year: "TE",
      tenure: "2026–2027",
      photoUrl: "",
      linkedinUrl: "https://linkedin.com",
      email: "sports.council@moderncoe.edu.in",
      displayOrder: 9,
      isActive: true,
    },
    {
      id: "mem-010",
      name: "Varun Nair",
      designation: "Secretary of Website Operations & Technical Infrastructure",
      wing: "SECRETARY",
      department: "AI & DS",
      year: "TE",
      tenure: "2026–2027",
      photoUrl: "",
      linkedinUrl: "https://linkedin.com",
      email: "webops.council@moderncoe.edu.in",
      displayOrder: 10,
      isActive: true,
    },
    {
      id: "mem-011",
      name: "Tanvi S. Kadam",
      designation: "Ladies’ Representative (LR) & Welfare Secretary",
      wing: "SECRETARY",
      department: "Computer Engineering",
      year: "TE",
      tenure: "2026–2027",
      photoUrl: "",
      linkedinUrl: "https://linkedin.com",
      email: "lr.council@moderncoe.edu.in",
      displayOrder: 11,
      isActive: true,
    },
    {
      id: "mem-012",
      name: "Pooja Gaikwad",
      designation: "NSS & Social Outreach Coordinator",
      wing: "SECRETARY",
      department: "Information Technology",
      year: "TE",
      tenure: "2026–2027",
      photoUrl: "",
      linkedinUrl: "https://linkedin.com",
      email: "nss.council@moderncoe.edu.in",
      displayOrder: 12,
      isActive: true,
    },
    {
      id: "mem-013",
      name: "Chinmayee Bapat",
      designation: "Magazine & Editorial Secretary ('Chaitanya')",
      wing: "SECRETARY",
      department: "Mechanical Engineering",
      year: "TE",
      tenure: "2026–2027",
      photoUrl: "",
      linkedinUrl: "https://linkedin.com",
      email: "editorial.council@moderncoe.edu.in",
      displayOrder: 13,
      isActive: true,
    },
    // Departmental Representatives (DRs for all 9 depts)
    {
      id: "mem-014",
      name: "Shreya More",
      designation: "Department Representative (DR)",
      wing: "DR",
      department: "Artificial Intelligence & Data Science",
      year: "TE",
      tenure: "2026–2027",
      photoUrl: "",
      email: "dr.aids@moderncoe.edu.in",
      displayOrder: 14,
      isActive: true,
    },
    {
      id: "mem-015",
      name: "Pranav Jagtap",
      designation: "Department Representative (DR)",
      wing: "DR",
      department: "Artificial Intelligence & Machine Learning",
      year: "TE",
      tenure: "2026–2027",
      photoUrl: "",
      email: "dr.aiml@moderncoe.edu.in",
      displayOrder: 15,
      isActive: true,
    },
    {
      id: "mem-016",
      name: "Gaurav Choudhary",
      designation: "Department Representative (DR)",
      wing: "DR",
      department: "Computer Engineering",
      year: "TE",
      tenure: "2026–2027",
      photoUrl: "",
      email: "dr.comp@moderncoe.edu.in",
      displayOrder: 16,
      isActive: true,
    },
    {
      id: "mem-017",
      name: "Sneha Kulkarni",
      designation: "Department Representative (DR)",
      wing: "DR",
      department: "Information Technology",
      year: "TE",
      tenure: "2026–2027",
      photoUrl: "",
      email: "dr.it@moderncoe.edu.in",
      displayOrder: 17,
      isActive: true,
    },
    {
      id: "mem-018",
      name: "Yashraj Mane",
      designation: "Department Representative (DR)",
      wing: "DR",
      department: "Electronics & Telecommunication",
      year: "TE",
      tenure: "2026–2027",
      photoUrl: "",
      email: "dr.entc@moderncoe.edu.in",
      displayOrder: 18,
      isActive: true,
    },
    {
      id: "mem-019",
      name: "Vaishnavi Gore",
      designation: "Department Representative (DR)",
      wing: "DR",
      department: "Electrical Engineering",
      year: "TE",
      tenure: "2026–2027",
      photoUrl: "",
      email: "dr.elect@moderncoe.edu.in",
      displayOrder: 19,
      isActive: true,
    },
    {
      id: "mem-020",
      name: "Samarth Salunkhe",
      designation: "Department Representative (DR)",
      wing: "DR",
      department: "Mechanical Engineering",
      year: "TE",
      tenure: "2026–2027",
      photoUrl: "",
      email: "dr.mech@moderncoe.edu.in",
      displayOrder: 20,
      isActive: true,
    },
    {
      id: "mem-021",
      name: "Mayuri Ranaware",
      designation: "Department Representative (DR)",
      wing: "DR",
      department: "Master of Computer Applications (MCA)",
      year: "SY",
      tenure: "2026–2027",
      photoUrl: "",
      email: "dr.mca@moderncoe.edu.in",
      displayOrder: 21,
      isActive: true,
    },
    {
      id: "mem-022",
      name: "Kunal Agarwal",
      designation: "Department Representative (DR)",
      wing: "DR",
      department: "Master of Business Administration (MBA)",
      year: "SY",
      tenure: "2026–2027",
      photoUrl: "",
      email: "dr.mba@moderncoe.edu.in",
      displayOrder: 22,
      isActive: true,
    },
    // Website Operations Team
    {
      id: "mem-023",
      name: "Harshvardhan R.",
      designation: "Lead Portal Architect & Full-Stack Engineer",
      wing: "WEB_OPS",
      department: "AI & DS",
      year: "TE",
      tenure: "2026–2027",
      photoUrl: "",
      linkedinUrl: "https://linkedin.com",
      email: "webteam@moderncoe.edu.in",
      displayOrder: 23,
      isActive: true,
    },
    {
      id: "mem-024",
      name: "Ritika Sonawane",
      designation: "UI/UX & Design Systems Lead",
      wing: "WEB_OPS",
      department: "Information Technology",
      year: "TE",
      tenure: "2026–2027",
      photoUrl: "",
      linkedinUrl: "https://linkedin.com",
      email: "webteam@moderncoe.edu.in",
      displayOrder: 24,
      isActive: true,
    },
  ],
  clubs: [
    {
      id: "club-001",
      name: "CoDE Club (Council of Data Engineering & AI)",
      acronym: "CoDE",
      category: "DEPARTMENTAL",
      department: "Artificial Intelligence & Data Science",
      description:
        "The official technical association of AI & DS students fostering machine learning projects, data hackathons, research symposiums, and industry mentorship.",
      leadName: "Arya Joshi",
      leadContact: "+91 98221 11223",
      instagramUrl: "https://instagram.com/code_mcoe",
      whatsappUrl: "https://whatsapp.com/channel/code_mcoe",
      featuredTags: ["AI & Data Science", "Hackathons", "Kaggle Meets"],
    },
    {
      id: "club-002",
      name: "IEEE MCOE Student Branch",
      acronym: "IEEE MCOE",
      category: "TECHNICAL_CHAPTER",
      department: "Inter-Departmental (E&TC, Comp, IT)",
      description:
        "The international technical chapter promoting research papers, embedded systems, IoT workshops, and global IEEE conferences.",
      leadName: "Siddhant Sawant",
      leadContact: "+91 97654 44556",
      instagramUrl: "https://instagram.com/ieee_pesmcoe",
      featuredTags: ["Robotics", "IoT", "Research Papers", "IEEE Xplore"],
    },
    {
      id: "club-003",
      name: "CSI Student Chapter (Computer Society of India)",
      acronym: "CSI MCOE",
      category: "TECHNICAL_CHAPTER",
      department: "Computer & Information Technology",
      description:
        "Premier technical society organizing algorithmic coding bootcamps, cybersecurity capture-the-flag (CTF), and cloud computing seminars.",
      leadName: "Neha Tambe",
      leadContact: "+91 98901 22334",
      instagramUrl: "https://instagram.com/csi_mcoe",
      featuredTags: ["Web Dev", "Cloud", "Cybersecurity", "DSA"],
    },
    {
      id: "club-004",
      name: "Purushottam & Firodiya Theatrical Troupe",
      acronym: "Kala Parishad",
      category: "CULTURAL",
      department: "Inter-Departmental Cultural Wing",
      description:
        "PES MCOE’s renowned Marathi and Hindi dramatic society competing at prestigious state-level Purushottam Karandak, Firodiya, and Srujan Karandak competitions.",
      leadName: "Sanket Kulkarni",
      leadContact: "+91 94220 88990",
      instagramUrl: "https://instagram.com/mcoe_natak",
      featuredTags: ["One-Act Plays", "Street Plays", "Purushottam Karandak"],
    },
    {
      id: "club-005",
      name: "Shaurya Sports Guild",
      acronym: "Shaurya",
      category: "SPORTS",
      department: "Department of Physical Education & Sports",
      description:
        "Coordinating university level athletics, box cricket leagues, futsal tournaments, and fitness camps across all 9 departments.",
      leadName: "Rohit Jadhav",
      leadContact: "+91 91580 99001",
      instagramUrl: "https://instagram.com/mcoe_shaurya",
      featuredTags: ["Cricket", "Football", "Volleyball", "Athletics"],
    },
    {
      id: "club-006",
      name: "NSS Cell (National Service Scheme, MCOE Unit)",
      acronym: "NSS MCOE",
      category: "SOCIAL_OUTREACH",
      department: "SPPU NSS Board Unit",
      description:
        "Dedicated to 'Not Me But You' through rural village adoption camps, river cleanups, disaster relief drives, and national social awareness campaigns.",
      leadName: "Pratiksha Patil",
      leadContact: "+91 93700 12340",
      instagramUrl: "https://instagram.com/nss_pesmcoe",
      featuredTags: ["Blood Donation", "Swachh Bharat", "Village Camps"],
    },
    {
      id: "club-007",
      name: "MESA (Mechanical Engineering Students Association)",
      acronym: "MESA",
      category: "DEPARTMENTAL",
      department: "Mechanical Engineering",
      description:
        "Organizers of CAD/CAM workshops, BAJA SAE motorsport design team, 3D printing masterclasses, and industrial plant visits.",
      leadName: "Tejas Gaikwad",
      leadContact: "+91 98230 45678",
      featuredTags: ["BAJA SAE", "SolidWorks", "Automotive Design"],
    },
    {
      id: "club-008",
      name: "ACES (Association of Computer Engineering Students)",
      acronym: "ACES",
      category: "DEPARTMENTAL",
      department: "Computer Engineering",
      description:
        "Conducting open source hack days, Linux installations, competitive programming circuits, and peer coding groups.",
      leadName: "Mrunal Joshi",
      leadContact: "+91 97640 12890",
      featuredTags: ["Open Source", "Algorithms", "DevOps"],
    },
  ],
  notices: [
    {
      id: "not-001",
      refNumber: "MCOE/SC/2026/08",
      title: "Call for Event Submissions & Rulebooks: M-PULSE 2027 National Tech Fest",
      category: "CIRCULAR",
      summary:
        "All departmental associations and technical cells are hereby notified to submit proposed sub-event tracks and jury rosters for M-PULSE 2027 by November 10, 2026.",
      pdfUrl: "#circular-mpulse-2027",
      fileSize: "420 KB",
      isPinned: true,
      publishedAt: "2026-10-04T10:00:00.000Z",
    },
    {
      id: "not-002",
      refNumber: "MCOE/SC/2026/07",
      title: "Notice: Extended Central Library Reading Room Timings for SPPU Winter 2026 Examinations",
      category: "TIMETABLE",
      summary:
        "In response to Students’ Council representation, Central Library Ground & Mezzanine halls will remain open until 10:00 PM starting Monday.",
      pdfUrl: "#library-extension-notice",
      fileSize: "280 KB",
      isPinned: true,
      publishedAt: "2026-09-29T14:30:00.000Z",
    },
    {
      id: "not-003",
      refNumber: "MCOE/SC/2026/06",
      title: "Auditions for Purushottam Karandak & Spandan 2027 Cultural Contingent",
      category: "ANNOUNCEMENT",
      summary:
        "Auditions for Drama, Street Play, Classical Vocals, and Western Band will be conducted on October 18–19 at the College Auditorium.",
      pdfUrl: "#cultural-auditions",
      fileSize: "350 KB",
      isPinned: false,
      publishedAt: "2026-09-25T11:00:00.000Z",
    },
    {
      id: "not-004",
      refNumber: "MCOE/SC/2026/05",
      title: "Official Students’ Council Constitution & Code of Conduct 2026–2027",
      category: "RULEBOOK",
      summary:
        "Official guidelines for portfolio secretaries, departmental representatives, and event coordinators governing student activities at PES MCOE.",
      pdfUrl: "#council-code-of-conduct",
      fileSize: "1.2 MB",
      isPinned: false,
      publishedAt: "2026-09-10T09:00:00.000Z",
    },
  ],
  eventRegistrations: [
    {
      id: "reg-001",
      referenceNumber: "MCOE-EVT-2026-1042",
      eventId: "evt-003",
      eventTitle: "HACK-AI 2027: 36-Hour National AI & Data Science Hackathon",
      studentName: "Devendra Patil",
      collegeName: "PES’s Modern College of Engineering, Pune",
      department: "Artificial Intelligence & Data Science",
      academicYear: "TE",
      prn: "72145892K",
      phone: "+91 98223 99881",
      email: "devendra.patil@moderncoe.edu.in",
      teamName: "NeuralWeavers",
      teamSize: 4,
      message: "Building an edge-AI vision system for automated municipal road anomaly detection.",
      status: "CONFIRMED",
      adminNotes: "Team verified with valid college PRN. Assigned Lab Table B-304.",
      isContacted: true,
      createdAt: "2026-10-02T15:20:00.000Z",
    },
    {
      id: "reg-002",
      referenceNumber: "MCOE-EVT-2026-1043",
      eventId: "evt-001",
      eventTitle: "M-PULSE 2027: National Level Technical Symposium",
      studentName: "Aniket Deshpande",
      collegeName: "COEP Technological University, Pune",
      department: "Computer Engineering",
      academicYear: "BE",
      prn: "COEP-19283",
      phone: "+91 94231 66554",
      email: "aniket.d@coep.ac.in",
      teamName: "CodeSentinels",
      teamSize: 2,
      message: "Registering for National Coding League & Project Expo.",
      status: "REGISTERED",
      adminNotes: "External college registration. ID card to be checked on spot.",
      isContacted: false,
      createdAt: "2026-10-04T11:45:00.000Z",
    },
  ],
  studentVoiceSubmissions: [
    {
      id: "voice-001",
      referenceNumber: "MCOE-VOICE-8412",
      category: "CLUB_PROPOSAL",
      studentName: "Shantanu Gokhale",
      department: "Artificial Intelligence & Machine Learning",
      academicYear: "SE",
      email: "shantanu.g@moderncoe.edu.in",
      phone: "+91 98810 44332",
      subject: "Proposal to start a Student Cloud & DevOps Study Jam under Google Cloud / AWS",
      message:
        "I would like to propose a 6-week weekend peer study jam covering Docker, Kubernetes, and Cloud Architecture for 2nd and 3rd year students. I have 10 interested volunteers.",
      status: "UNDER_REVIEW",
      adminNotes: "Discussed with Secretary of Web Ops. Scheduled meeting with SDO on Wednesday.",
      isReviewed: true,
      createdAt: "2026-10-03T14:10:00.000Z",
    },
    {
      id: "voice-002",
      referenceNumber: "MCOE-VOICE-8413",
      category: "VOLUNTEERING",
      studentName: "Sayali Kulkarni",
      department: "Information Technology",
      academicYear: "FE",
      email: "sayali.k@moderncoe.edu.in",
      phone: "+91 97650 33221",
      subject: "Volunteering for M-Pulse 2027 Technical Event Operations and Registration Desk",
      message:
        "First-year IT student keen to volunteer for registration desk coordination, stage management, and social media coverage for M-Pulse 2027.",
      status: "RECEIVED",
      adminNotes: "",
      isReviewed: false,
      createdAt: "2026-10-05T09:30:00.000Z",
    },
  ],
  sponsorshipEnquiries: [
    {
      id: "spon-001",
      referenceNumber: "MCOE-SPON-5120",
      organizationName: "Persistent Systems Campus Connect",
      contactPerson: "Mahesh Kadam (Talent Acquisition Lead)",
      email: "campus_outreach@persistent.com",
      phone: "+91 20 6703 0000",
      partnershipType: "TITLE_SPONSOR",
      targetEvent: "M-PULSE 2027 & HACK-AI 2027",
      message:
        "Interested in title sponsorship for the 36-Hour Hackathon with hackathon challenge tracks, hiring access to top finalists, and keynote slot during inaugural ceremony.",
      status: "IN_DISCUSSION",
      adminNotes: "Meeting scheduled with General Secretary & Faculty Advisors next Friday.",
      isContacted: true,
      createdAt: "2026-10-01T17:00:00.000Z",
    },
    {
      id: "spon-002",
      referenceNumber: "MCOE-SPON-5121",
      organizationName: "Red Bull India (Pune Campus Wing)",
      contactPerson: "Akash Sharma",
      email: "akash.sharma@redbull.in",
      phone: "+91 98200 88776",
      partnershipType: "STALL_PARTNER",
      targetEvent: "SPANDAN 2027 & SHAURYA Sports Meet",
      message:
        "Energy drink sampling zone and gaming booth setup during 3 days of Spandan cultural gathering.",
      status: "NEW",
      adminNotes: "",
      isContacted: false,
      createdAt: "2026-10-05T13:40:00.000Z",
    },
  ],
};
